repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.0.1
    hooks:
      - id: eslint
        name: ESLint
        files: \.(js|jsx|ts|tsx)$
