version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:3000"  # Host port 5000 maps to container port 3000
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/social_network
    restart: always

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: social_network
    ports:
      - "5432:5432"
    restart: always
